### ISSUE TITLE
YAML::PP::LibYAML not "serious"?

### ISSUE THREAD

**Issue by perlpunk** [briandfoy/yaml-module-test#1]
You write in the README.md:

> ## YAML::PP::LibYAML
> * Never really made much progress as a serious module

This sounds strange to me. Feel free to try it out. The fact that it has no votes on metacpan or only one star on github doesn't say that it's not serious.
Did you find problems with it?
The only downside might be, that it's an XS module, and the C code in it is not battletested yet. The libyaml part of it is, though.

**Comment by briandfoy** [comment]
Well, it's at version 0.005 and it's almost two years old with no recent effort. You say "not battletested yet", and it doesn't look like anyone is working on it. That's the "never really made much progress part". To me it looks abandoned. If that's not the case, someone should release a version with a version number that indicates it's ready for use. 

Also, the "PP" name in an XS module is really odd. I figured there was stuff to work out there.

**Comment by perlpunk** [comment]
> Well, it's at version 0.005

Oh, come on. YAML::XS also has a version with a zero in front.

> and it's almost two years old with no .

pretty much exactly 1.5 years.

>You say "not battletested yet", and it doesn't look like anyone is working on it.

I need users to try it out in different scenarios. I did my best to avoid memory leaks, as I am already familiar with YAML::XS where I also removed a memory leak, but I don't know of anyone running my module in production.

I'm just complaining about the wording. I'm not a native english speaker, but to me your sentence sounds like the module was just an experiment.

So people see the version number and the 1.5 year age, and _might_ be skeptical. But now if they see your project and read that it's not a serious module, nobody's going to try it out. Great.

> That's the "never really made much progress part". To me it looks abandoned. If that's not the case, someone should release a version with a version number that indicates it's ready for use.
> 
> Also, the "PP" name in an XS module is really odd. I figured there was stuff to work out there.

To clarify that one, [YAML::PP::LibYAML](https://metacpan.org/pod/YAML::PP::LibYAML) itself is not the XS module, that was inaccurate from me. The XS module is [YAML::LibYAML::API](https://metacpan.org/pod/YAML::LibYAML::API).

YAML::PP is a framework that allows to use different loaders, dumpers, parsers and emitters.
YAML::LibYAML::API is a thin XS wrapper around the libyaml parser and emitter.
YAML::PP::LibYAML connects the YAML::PP loader/dumper frontend with the parser/emitter backend from YAML::LibYAML::API.

I know that this sounds confusing if one doesn't know that about YAML::PP.
The only alternative I can think of is to put the connector module into the XS module itself, e.g. YAML::LibYAML::API::YAMLPP, but that's not looking nice either.

---
Just wanted to clarify these things. Leave things as they are if you want. That's all.

**Comment by briandfoy** [comment]
Hey Tina, I've known your name forever and I know that you do really good work. You're the YAML expert that the world needs and that the world should listen to. 

That doesn't change the fact that almost everything about [YAML::PP::LibYAML](https://metacpan.org/pod/YAML::PP::LibYAML) and [YAML::LibYAML::API](https://metacpan.org/pod/YAML::LibYAML::API) looks like it's not something that may be maintained. It does look like an experiment. 

Sure, YAML::XS has 0 as the major version number, but it's also had tens of releases from several developers over a long time. And, people use it. Maybe they shouldn't use it, but they do and it's one of the modules I have to deal with because I often don't have a say in the matter. 

That's a lot different with a module that then has zeros right after the decimal place. 0.005 is how we signal to people that they shouldn't use this in production or in any other scenario where they have long term maintenance concerns. [YAML::LibYAML::API](https://metacpan.org/pod/YAML::LibYAML::API), the very minimal docs on the main module has this line:

> This is just one of the first releases. The function names will eventually be changed.

That's a big red flag.

And, there's a year-old issue for that module that notes the two modules are violating the MIT license for libyaml. That's a bit of a problem for people who care about licenses. It's an easy fix, so I don't know why it's still an issue after a year. It doesn't look like you care that much about making it useful to people who have to abide by licenses.

The more you try to explain it in this thread, the worse it sounds to me and the less I want to use it. And, that has nothing to do with the actual quality of the module or the skills of its programmer.
